In [1]:
import os, sys
os.environ.setdefault('CONDA_PREFIX', sys.prefix)
os.environ.get('CONDA_PREFIX')

'/opt/conda/envs/python3'

In [2]:
from sklearn.datasets import load_iris
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import f1_score
import numpy as np
import sys

In [3]:
import pandas as pd

from importlib import reload
import cuml
import cupyx.scipy.sparse as cps
import cuml.internals.array_sparse as arrsp
import cupyx.scipy.sparse._compressed as cpsc
import cupy as cp

In [4]:
data = pd.read_csv("../data/data_stemmed.csv", index_col=0)
data.shape

(994988, 1)

In [5]:
metadata = pd.read_csv("../data/995,000_rows.csv", usecols=["type"])
metadata.shape

(995000, 1)

In [6]:
vocab_list = pd.read_csv("../data/topwords10000.csv", index_col=0)

In [7]:
def change_label(label):
    if label in ["fake","clickbait","hate","rumor","unreliable","conspiracy","unknown"]:
        return "fake"
    else:
        return "reliable"

In [8]:
metadata_values, metadata_classes = pd.factorize(metadata["type"].apply(change_label))
metadata_classes

Index(['reliable', 'fake'], dtype='object')

In [13]:
data["type"] = pd.Series(metadata_values)
data

                                                  content  type
0       plus one articl googl plus ( thank ali alfoneh...     0
1       cost best senat bank committe jp morgan buy : ...     1
2       man awoken <num> -year coma commit suicid lear...     0
3       julia geist ask draw pictur comput scientist l...     0
4       – <num> compil studi vaccin danger ( activist ...     1
...                                                   ...   ...
994995  <num> wire + intervent watch | say anyon sign ...     1
994996  plus one articl googl plus ( thank ali alfoneh...     0
994997  china russia acquir gold , dump us dollar evid...     1
994998  liverpool sign sadio mane southampton fan reac...     1
994999  cnn promot coup venezuela - maduro monday pres...     0

[994988 rows x 2 columns]

In [14]:
data_training = data[0:int(len(data)*0.8)]
data_validation = data[int(len(data)*0.8):int(len(data)*0.9)]
data_testing = data[int(len(data)*0.9):]

In [15]:
vocab_words = vocab_list.index.to_numpy()

In [16]:
vectorizer = CountVectorizer(vocabulary=vocab_words)
vectorizer

CountVectorizer(vocabulary=array([',', '.', '<num>', ..., 'omb-', 'gds', 'last-ditch'],
      shape=(10000,), dtype=object))

In [48]:
X = vectorizer.transform(data_training["content"])
y = data_training["type"]
#analyze = vectorizer.build_analyzer()

In [49]:
y

0         0
1         1
2         0
3         0
4         1
         ..
795995    1
795996    0
795997    0
795998    0
795999    0
Name: type, Length: 795990, dtype: int64

In [50]:
model = cuml.LogisticRegression(max_iter=2500)
model

LogisticRegression()

In [62]:
model.fit(X, y)

LogisticRegression()

In [52]:
sample_test = data_training["type"].iloc[:20]

In [53]:
predict_test = X[:20, :]

In [63]:
model_sklearn = model.as_sklearn() 
model_sklearn

LogisticRegression(max_iter=2500)

In [64]:
model_sklearn.fit(X, y)

LogisticRegression(max_iter=2500)

In [65]:
sample_predict = model_sklearn.predict(predict_test)

In [66]:
test_results = pd.DataFrame({"actual": sample_test, "predicted": cp.asnumpy(sample_predict)})
test_results

    actual  predicted
0        0          0
1        1          1
2        0          0
3        0          0
4        1          1
5        0          0
6        0          0
7        0          0
8        1          0
9        0          0
10       0          0
11       0          0
12       1          1
13       1          0
14       1          1
15       0          0
16       0          0
17       1          0
18       1          1
19       1          1

In [70]:
true_y = data_validation["type"]
pred_y = model_sklearn.predict(vectorizer.transform(data_validation["content"]))

In [74]:
pred_y_gpu = model.predict(vectorizer.transform(data_validation["content"]))

ValueError: Only bool, float32, float64, complex64 and complex128 are supported

In [71]:
validation_results = pd.DataFrame({"actual": true_y, "predicted": cp.asnumpy(pred_y), "predcpu": pred_y_gpu})
validation_results

        actual  predicted
796000       0          0
796001       0          1
796002       0          1
796003       0          0
796004       1          1
...        ...        ...
895495       1          1
895496       0          0
895497       1          1
895498       1          0
895499       1          0

[99499 rows x 2 columns]

In [72]:
validation_results[60:75]

        actual  predicted
796060       1          1
796061       0          0
796062       1          0
796063       0          0
796064       1          1
796065       0          0
796066       1          1
796067       0          0
796068       0          0
796069       1          0
796070       0          0
796071       0          0
796072       1          1
796073       0          0
796074       0          0

In [73]:
f1_score(true_y, pred_y, average=None)

array([0.86591323, 0.77508241])